<?php

namespace ChasseBundle\Repository;

/**
 * IntAnsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntAnsRepository extends \Doctrine\ORM\EntityRepository
{
}
